apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    # path to the folder with the YAML manifests
    path: k8smanifests/
    repoURL: https://github.com/monikamikhaiel/
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}
