# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on: push 
jobs:
  docker_registery:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
#docker:
    steps:
# extract the latest version of the code 
      - name: Check out the repo
        uses: actions/checkout@v2
# execution environment for containers 
      - name: set up QEMU
        uses: docker/setup-qemu-action@v1
# build the container 
      - name: set up Docker buildx 
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
# current repository 
          context: ./webFiles/
#file: ./webFiles/Dockerfile
          push: true
          tags: monikamikhaiel/hello-world-go:v0.1
#labels: ${{ steps.meta.outputs.labels }}
